name: Lighthouse CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build project
        working-directory: ./frontend
        run: npm run build

      - name: Install serve
        working-directory: ./frontend
        run: npm install -g serve

      - name: Start server
        working-directory: ./frontend
        run: serve -s dist -l 8080 &

      - name: Wait for server
        run: sleep 5

      - name: Install Lighthouse CI
        working-directory: ./frontend
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        working-directory: ./frontend
        run: |
          lhci collect --url=http://localhost:8080/ \
                       --url=http://localhost:8080/dashboard \
                       --url=http://localhost:8080/calendario \
                       --url=http://localhost:8080/actividades/examenes \
                       --url=http://localhost:8080/actividades/extras \
                       --url=http://localhost:8080/actividades/proyectos \
                       --url=http://localhost:8080/actividades/tareas \
                       --url=http://localhost:8080/profile \
                       --url=http://localhost:8080/settings \
                       --url=http://localhost:8080/notificaciones \
                       --url=http://localhost:8080/cargaSemanal \
                       --url=http://localhost:8080/reportes \
                       --url=http://localhost:8080/editProfile \
                       --url=http://localhost:8080/login \
                       --url=http://localhost:8080/register
          lhci upload --target=temporary-public-storage


      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lhci-report
